export const GLOBAL_ARIA_ATTRIBUTES = [
    'aria-atomic',
    'aria-busy',
    'aria-controls',
    'aria-current',
    'aria-describedby',
    'aria-details',
    'aria-dropeffect',
    'aria-flowto',
    'aria-grabbed',
    'aria-hidden',
    'aria-keyshortcuts',
    'aria-live',
    'aria-owns',
    'aria-relevant',
    'aria-roledescription',
]

export const ARIA_ROLE_ALLOWED_ATTRIBUTES: Record<string, string[]> = {
    'aria-activedescendant': [
        'application',
        'combobox',
        'composite',
        'group',
        'textbox',
        'grid',
        'listbox',
        'menu',
        'menubar',
        'radiogroup',
        'row',
        'searchbox',
        'select',
        'spinbutton',
        'tablist',
        'toolbar',
        'tree',
        'treegrid',
        'option',
        'rowgroup',
    ],
    'aria-autocomplete': ['combobox', 'searchbox', 'textbox'],
    'aria-checked': [
        'checkbox',
        'menuitemcheckbox',
        'option',
        'radio',
        'switch',
        'menuitemradio',
        'treeitem',
    ],
    'aria-colcount': ['grid', 'treegrid'],
    'aria-colindex': ['grid', 'row', 'columnheader', 'gridcell', 'rowheader'],
    'aria-colspan': ['cell', 'columnheader', 'rowheader'],
    'aria-disabled': [
        'application',
        'button',
        'checkbox',
        'composite',
        'columnheader',
        'combobox',
        'grid',
        'gridcell',
        'group',
        'input',
        'link',
        'menuitem',
        'scrollbar',
        'separator',
        'tab',
        'listbox',
        'menu',
        'menubar',
        'menuitemcheckbox',
        'menuitemradio',
        'option',
        'radio',
        'radiogroup',
        'row',
        'rowheader',
        'searchbox',
        'select',
        'slider',
        'spinbutton',
        'switch',
        'tablist',
        'textbox',
        'toolbar',
        'tree',
        'treegrid',
        'treeitem',
    ],
    'aria-errormessage': [
        'application',
        'checkbox',
        'combobox',
        'gridcell',
        'listbox',
        'radiogroup',
        'slider',
        'spinbutton',
        'textbox',
        'tree',
        'columnheader',
        'rowheader',
        'searchbox',
        'switch',
        'treegrid',
    ],
    'aria-expanded': [
        'application',
        'button',
        'checkbox',
        'combobox',
        'gridcell',
        'link',
        'listbox',
        'menuitem',
        'row',
        'rowheader',
        'tab',
        'treeitem',
        'columnheader',
        'menuitemcheckbox',
        'menuitemradio',
        'switch',
    ],
    'aria-haspopup': [
        'application',
        'button',
        'combobox',
        'gridcell',
        'link',
        'menuitem',
        'slider',
        'tab',
        'textbox',
        'treeitem',
        'columnheader',
        'menuitemcheckbox',
        'menuitemradio',
        'rowheader',
        'searchbox',
    ],
    'aria-invalid': [
        'application',
        'checkbox',
        'combobox',
        'gridcell',
        'listbox',
        'radiogroup',
        'slider',
        'spinbutton',
        'textbox',
        'tree',
        'columnheader',
        'rowheader',
        'searchbox',
        'switch',
        'treegrid',
    ],
    'aria-level': ['heading', 'listitem', 'row', 'treeitem'],
    'aria-modal': ['alertdialog', 'dialog'],
    'aria-multiline': ['textbox', 'searchbox'],
    'aria-multiselectable': ['grid', 'listbox', 'tablist', 'tree', 'treegrid'],
    'aria-orientation': [
        'scrollbar',
        'select',
        'separator',
        'slider',
        'tablist',
        'toolbar',
        'listbox',
        'menu',
        'menubar',
        'radiogroup',
        'tree',
        'treegrid',
    ],
    'aria-placeholder': ['searchbox', 'textbox'],
    'aria-posinset': [
        'article',
        'listitem',
        'menuitem',
        'option',
        'radio',
        'row',
        'tab',
        'menuitemcheckbox',
        'menuitemradio',
        'treeitem',
    ],
    'aria-pressed': ['button'],
    'aria-readonly': [
        'checkbox',
        'combobox',
        'grid',
        'gridcell',
        'listbox',
        'radiogroup',
        'slider',
        'spinbutton',
        'textbox',
        'columnheader',
        'rowheader',
        'searchbox',
        'switch',
        'treegrid',
    ],
    'aria-required': [
        'checkbox',
        'combobox',
        'gridcell',
        'listbox',
        'radiogroup',
        'spinbutton',
        'textbox',
        'tree',
        'columnheader',
        'rowheader',
        'searchbox',
        'switch',
        'treegrid',
    ],
    'aria-rowcount': ['grid', 'treegrid'],
    'aria-rowindex': ['grid', 'row', 'columnheader', 'gridcell', 'rowheader'],
    'aria-rowspan': ['cell', 'columnheader', 'rowheader'],
    'aria-selected': [
        'grid',
        'option',
        'row',
        'tab',
        'columnheader',
        'rowheader',
        'treeitem',
    ],
    'aria-setsize': [
        'article',
        'listitem',
        'menuitem',
        'option',
        'radio',
        'row',
        'tab',
        'menuitemcheckbox',
        'menuitemradio',
        'treeitem',
    ],
    'aria-sort': ['columnheader', 'rowheader'],
    'aria-valuemax': [
        'range',
        'scrollbar',
        'separator',
        'meter',
        'progressbar',
        'slider',
        'spinbutton',
    ],
    'aria-valuemin': [
        'range',
        'scrollbar',
        'separator',
        'meter',
        'progressbar',
        'slider',
        'spinbutton',
    ],
    'aria-valuenow': [
        'range',
        'scrollbar',
        'separator',
        'meter',
        'progressbar',
        'slider',
        'spinbutton',
    ],
    'aria-valuetext': [
        'range',
        'scrollbar',
        'separator',
        'meter',
        'progressbar',
        'slider',
        'spinbutton',
    ],
}

export const ARIA_LABEL_FORBIDDEN_ROLES: string[] = [
    'caption',
    'code',
    'deletion',
    'emphasis',
    'generic',
    'insertion',
    'paragraph',
    'presentation',
    'strong',
    'subscript',
    'superscript',
]
