name: Full Accessibility Audit
on: [ push, pull_request ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies & Start App
        run: |
          npm ci
          echo "Starting Vite Server"
          npx vite --host &

          echo "Waiting for local Port 5173"
          npx wait-on http://localhost:5173 --timeout 60000
          echo "Vite can be reached locally"

      - name: Debug Network Info
        run: |
          echo "Host IP Information:"
          ip addr | grep eth0
          echo "Check if Port 5173 can be reached"
          sudo lsof -i :5173 || echo "Port 5173 cannot be reached"

      - name: Run Full Accessibility Audit With Docker
        run: |
          mkdir -p reports
          docker build -t full-accessibility-audit .

          GATEWAY_IP=$(docker network inspect bridge -f '{{ (index .IPAM.Config 0).Gateway }}')
          echo "Gateway IP is: $GATEWAY_IP"

          docker run --rm \
            --ipc=host \
            -e CYPRESS_BASE_URL="http://$GATEWAY_IP:5173" \
            --add-host=host.docker.internal:host-gateway \
            -v ${{ github.workspace }}/reports:/app/cypress/fixtures \
            full-accessibility-audit \
            sh -c "
              echo 'Testing connection to $GATEWAY_IP:5173' && \
              npx wait-on http://$GATEWAY_IP:5173 --timeout 60000 && \
              npm run cy:run-crawler && \
              npm run cy:run-audit
            "

      - name: Upload Report Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: full-accessibility-reports
          path: reports/
