name: Full Accessibility Audit

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: "24"
        description: "node.js version to use"

      app_port:
        required: true
        type: string
        description: "provide the correct port for your local server"

      base_path:
        required: false
        type: string
        default: "/"
        description: "optional base path appended to localhost"

      start_command:
        required: true
        type: string
        description: "provide the command to start your local server with the correct port and host flags"

      skip_crawler:
        required: false
        type: boolean
        default: false
        description: "skip crawler and run audit directly"

jobs:
  Full_Accessibility_Audit:
    name: Full Accessibility Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Client-App
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"

      - name: Start App
        run: |
          npm ci
          ${{ inputs.start_command }} &
          npx wait-on http://localhost:${{ inputs.app_port }}${{ inputs.base_path }} --timeout 60000

      - name: Run Full Accessibility Audit via GHCR Image
        run: |
          mkdir -p audit
          cp cypress/fixtures/sitemap.json audit/sitemap.json || echo '{"config": {"only": [], "included": [], "excluded": []}, "urls": []}' > audit/sitemap.json

          GATEWAY_IP=$(docker network inspect bridge -f '{{ (index .IPAM.Config 0).Gateway }}')

          if [ "${{ inputs.skip_crawler }}" = "true" ]; then
            AUDIT_COMMAND="npm run cy:run-audit"
          else
            AUDIT_COMMAND="npm run cy:run-crawler && npm run cy:run-audit"
          fi

          BASE_URL="http://$GATEWAY_IP:${{ inputs.app_port }}${{ inputs.base_path }}"

          docker run --rm \
            --ipc=host \
            -e CYPRESS_BASE_URL="$BASE_URL" \
            --add-host=host.docker.internal:host-gateway \
            -v ${{ github.workspace }}/audit:/app/cypress/fixtures \
            ghcr.io/stackoverflowisbetterthananyai/full-accessibility-audit:latest \
            sh -c "
              npx wait-on $BASE_URL --timeout 60000 && \
              $AUDIT_COMMAND
            "

      - name: Upload Audit
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: full-accessibility-audit
          path: audit/
